### ISSUE TITLE
A GAE-compatible version of EFB

### ISSUE THREAD

**Issue by thedogb** [blueset/ehForwarderBot#113]
感觉自己购买的vps来跑这个，经常报网络不稳定的通知，而且有时候消息延迟比较大。感觉这样一个项目应该可以部署到gae上，google的网络应该会稳定很多，而且gae的免费额度对于个人来说应该也够用。不知道是否有计划将这个应用移植到gae上

**Comment by blueset** [comment]
由于本人目前不是很了解 GAE 的工作原理和方式，所以暂时没有这个计划，同时，EFB 作为一个框架，其复杂度和个性化程度较高，可能不太适合 GAE。不过如果你找到了就于现行框架结构下的一些可行方案，也可在此提出。

**Comment by goodosoft** [comment]
期待gae版本

**Comment by ys-xue** [comment]
我暂时的做法是创建一个最低配置的Google Cloud Compute Engine, 然后用`screen`保持efb在后台运行，不过这样最多只能用一年，promotional credits就会过期了

**Comment by blueset** [comment]
After some readings on the docs of Google App Engine (GAE) environment for Python 3, it seems like GAE requires the program to be a Gunicorn-based web server, which EFB is not. And it seems like this server-less settings would make it difficult to do setups, CLI interactions, or to install missing dependencies (e.g. Docker required by QQ Slave channel).

I would close this issue for now due to the perceived hurdle of GAE. However, fi anyone is aware of any method to fit EFB into GAE, leave a comment here so we can discuss about it.
