### ISSUE TITLE
how about creating a conda channel named efb?

### ISSUE THREAD

**Issue by specter119** [blueset/ehForwarderBot#131]
How about add all your packages into a conda channel named efb, since most linux distributions use py3.5 as default python3 version. Therefore, using miniconda will be more easy to build the necessary environment efficiently.

then the install command should something like:

```sh
conda install ehForwarderBot -c efb
# or
conda create -n efb ehForwarderBot -c efb
```

**Comment by blueset** [comment]
Thanks for the suggestion. 

We will consider this as an alternative to #126 when stable versions are released.

**Comment by specter119** [comment]
@blueset Thanks, I will still vote for conda channel since it will reduce a lot of issue related to distributions difference.

The only problem I met when install all your packages it that the Pillow doesn't support webp natively, but I can still install libwebp directly within conda, and reinstall pillow by pip. I think it's much more easier than installing python independently, and then pip etc..

**Comment by blueset** [comment]
I have just briefly read Conda's docs about conda channels. It seems like running a conda channel requires extensive server resources for an infrastructure of package hostings. If that is the case, I don't currently have the resource and time to manage one. But anyway I am not familiar with the conda ecosystem, so correct me if I am wrong.

In the meanwhile there are also other options like docker images and AUR packages (thanks!) contributed by the community that could serve as an alternative to this. 

I am closing this for now since no update is found in the past 1+ years, but feel free to bring out your ideas on this anyway!
