### ISSUE TITLE
EWS times out after 12 hours of inactivity

### ISSUE THREAD

**Issue by Tenzer** [blueset/ehForwarderBot#48]
I've written a eh_hipchat_master plugin which I'm using to bridge to WeChat, and I'm seeing the WeChat connection time out consistently after 12 hours of inactivity.

I haven't tried to use ehForwarderBot with the Telegram master, so I'm not aware of the same is the case when using that, but I was wondering if it would make sense to make a keep alive system for WeChat, so it for instance sends a message to the File Helper user at a set interval, in order to avoid it being disconnected? It seems like that also could solve the problem another user reported in #37.

If it's not a problem when using the Telegram master, I could instead just add a keep alive message being sent from the Hipchat master, but it seems a bit odd since it's not related to the Hipchat part at all.

**Comment by blueset** [comment]
Hi @Tenzer ! As per experiment, to keep a WeChat Web session online, the mobile client used must be kept online for most of the time, if not always. From the feedback from users, WeChat server does sometime indeterminately turn off the connection with or without notifying the web client. 

Despite the would be absolutely no guarantee of its stability, not even for the pure web client, it isn't normal to timeout every 12 hours. It would be better if you can provide some verbose log (at level `-vv`) related to it, so that we can diagnose if it's the issue with EWS.

After all, the so-called Web WeChat "API", and its wrap `littlecodersh/itchat`, is just a hack — it doesn't work much better even in a normal web browser. Tencent isn't focusing much on it as well. It's of course not as comparable to the Android/iOS app version, nor to the web version of Telegram/FB Messenger.

By the way:
* About the channel ID, it's usually named in the format of `<AUTHOR>_<PLATFORM>_<TYPE>` e.g. `lorem_slack_master`. It would be nice to have a more unique name if you feel like to publish your channel. [^1](https://ehforwarderbot.readthedocs.io/en/latest/slave-channel/) (Sorry for the badly organised docs)
* I'm planning to write EFB v2 probably starting this July. In general, the installation will be easier and the EFB interface will be more organised. [Current plan](https://github.com/blueset/ehForwarderBot/projects/1).
