### ISSUE TITLE
 Error while getting Updates: Timed out

### ISSUE THREAD

**Issue by Hstripe** [blueset/ehForwarderBot#94]
When I execute 'python3 daemon.py start'
console log:
"
Error count: 1185
\Timed out
Update: None
2017-11-13 01:54:08,878: telegram.ext.updater [ERROR]
    Error while getting Updates: Timed out
2017-11-13 01:54:08,879: plugins.eh_telegram_master.TelegramChannel [ERROR]
    Poor internet connection detected.
Error count: 1186
\Timed out
Update: None"

How can I solve this problem?

**Comment by blueset** [comment]
If your log starts with this, it means you have already started an EFB daemon, it prints the latest lines of log to the console instead. The `Timed out` error means there was intermittent interruption in the  connection between your server and Telegram Bot API.
If it does not affect your use, you can simply ignore it. Otherwise, you may need to switch to another server with a better network environment.

**Comment by Hstripe** [comment]
Thanks for u advise
